# List Comprehensions
List comprehensions can replace many for statements that iterate over existing sequences and create new lists.

In [282]:
#filling a list with for loop

lst1=[]
for i in range(6):
  lst1.append(i)
lst1

[0, 1, 2, 3, 4, 5]

In [284]:
#filling a list with list comprehension

lst2 = [i*3 for i in range(6)]
lst2

[0, 3, 6, 9, 12, 15]

## Performing Operations in a List Comprehension’s Expression

In [285]:
lst3 = [i**3 for i in range(6)]
lst3

[0, 1, 8, 27, 64, 125]

## List Comprehensions with if Clauses (to filter elements)
we can filter elements to select only those that match a condition<br>
حاصل آن لیستی با عناصر کمتر است

In [286]:
lst4 = [i for i in range(10)]
lst4

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [287]:
lst5 = [i for i in range(10) if i % 2 == 0]
lst5

[0, 2, 4, 6, 8]

In [289]:
lst6 = [i+7 for i in range(10) if i % 2 == 0]
lst6

[7, 9, 11, 13, 15]

In [291]:
def is_odd(x):
    return x % 2 != 0

[i+6 for i in range(10) if is_odd(i)]

[7, 9, 11, 13, 15]

In [292]:
lst7=[x+1 if x%2==0 else "nope" for x in range(10)]
lst7

[1, 'nope', 3, 'nope', 5, 'nope', 7, 'nope', 9, 'nope']

In [6]:
lst8=[]
for x in range(10):  
    if x%2==0:
        lst8.append(x+1)
    else:
        lst8.append('nope')
lst8


[1, 'nope', 3, 'nope', 5, 'nope', 7, 'nope', 9, 'nope']

In [293]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [296]:
[y for x in list_of_list for y in x]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [297]:
lst10=[]
for x in list_of_list:
    for y in x:
        lst10.append(y)
lst10

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [300]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

[[row[i] for row in matrix] for i in range(3)]

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [301]:
transposed = []

for i in range(3):
    transposed_row = []
    for row in matrix:
            transposed_row.append(row[i])
    transposed.append(transposed_row)
transposed

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [19]:
matrix = [[0 for col in range(4)] for row in range(3)]

matrix

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

### Instead of range, you can use another list for your loop's iterator

In [302]:
colors = ['red', 'orange', 'yellow', 'green', 'blue']
lst9=[i.upper() for i in colors]
lst9

['RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE']

___________

# Lambda
For simple functions that return only a single expression’s value, you can use a lambda expression<br>
A lambda expression is an anonymous function. It means it's **a function without a name**.

def function_name(*parameter_list*): <br>
$\hspace{1cm}$ return **expression** <br><br>
lambda *parameter_list*: **expression**

In [304]:
(lambda x: x**2 -2*x +1)(3)

4

In [273]:
colors

['red', 'orange', 'yellow', 'green', 'blue']

In [30]:
list(map(lambda x: x.upper() , colors))

['RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE']

In [305]:
def apply_twice(func, arg):

  return func(func(arg))

apply_twice(lambda x: x+7, 5)

19

In [306]:
def apply_twice(func, arg):

  return func(func(arg))

def func(x):
    return x+7

apply_twice(func,5)

19

In [307]:
def my_func(func, arg):

  return func(arg)



my_func(lambda x: 2*x*x, 5)

50

In [308]:
double = lambda x: x * 2

double(7)

14

# Two-Dimensional Lists
Lists that require two indices to identify an element are called two-dimensional lists. Multidimensional lists can have
more than two indices.

In [309]:
a = [[77, 68, 86, 73],
     [96, 87, 89, 81],
     [70, 90, 86, 81]]

In [311]:
a[0][2]

86

In [313]:
a[2][1]

90

In [314]:
a[1][1]

87

|| Column 0| Column 1 | Column 2 | Column 3|
|---|----|------|-----|------|
|**Row0**|77|68|86|73|
|**Row1**|96|87|89|81|
|**Row2**|70|90|86|81|

|| Column 0| Column 1 | Column 2 | Column 3|
|---|----|------|-----|------|
|**Row0**|a[0][0]|a[0][1]|a[0][2]|a[0][3]|
|**Row1**|a[1][0]|a[1][1]|a[1][2]|a[1][3]|
|**Row2**|a[2][0]|a[2][1]|a[2][2]|a[2][3]|

In [315]:
for i,row in enumerate(a):
    for j,item in enumerate(row):
        print(f"a[{i}][{j}]={item} ,")

a[0][0]=77 ,
a[0][1]=68 ,
a[0][2]=86 ,
a[0][3]=73 ,
a[1][0]=96 ,
a[1][1]=87 ,
a[1][2]=89 ,
a[1][3]=81 ,
a[2][0]=70 ,
a[2][1]=90 ,
a[2][2]=86 ,
a[2][3]=81 ,


# Numpy
Operations on arrays are up to two orders of magnitude faster than
those on lists

### First step, importing Numpy!

In [1]:
import numpy as np

In [318]:
lst=[1,2,3,4,5,6]

num= np.array(lst)

print(type(num))
print(num)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [320]:
type(np.array([[1, 2, 3], [9, 5, 6]]))

numpy.ndarray

### array Attributes

#### 1. dtype

In [327]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers.astype('int64')

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [325]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats.dtype

dtype('float64')

#### 2. ndim
ndim contains an array’s **number** of dimensions

In [328]:
integers.ndim

2

In [329]:
floats.ndim

1

#### 3.shape
the attribute shape
contains a tuple specifying an array’s dimensions

In [330]:
integers.shape

(2, 3)

In [331]:
floats.shape

(5,)

#### 4.size
returns array’s total number of elements

In [172]:
integers.size

6

In [332]:
floats.size

5

### flatten()
converts multidimensional array to a one dimensional array.<br>
Method flatten deep copies the original array’s data.

In [333]:
a=integers.flatten()
a

array([1, 2, 3, 4, 5, 6])

In [334]:
integers #so faletten only makes a copy and doesn't alter the original array

array([[1, 2, 3],
       [4, 5, 6]])

In [335]:
a[0]=44
a

array([44,  2,  3,  4,  5,  6])

In [336]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

### Filling arrays with Specific Values

In [337]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [339]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [340]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [341]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [342]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

### Creating Integer Ranges with
 $\hspace{1cm}$ **arange** function <br>
 
 it's kinda similar to *range* build-in fuction

In [66]:
np.arange(5)

array([0, 1, 2, 3, 4])

### evenly spaced values

In [344]:
np.linspace(0.0, 10, num=5) #num's default value is 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### reshape
you can use array method reshape to transform the one-dimensional array into a multidimensional array.<br>
Method reshape returns a view **(shallow copy)** of the original array with the new dimensions.
It does not modify the shape of original array.

In [3]:
s=np.arange(1, 21)
s.shape

(20,)

In [7]:
re_s=(s.reshape(5,4))
re_s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [8]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
re_s[0]

array([1, 2, 3, 4])

In [10]:
re_s[0]=np.array([5,5,5,5])
print(re_s)
print(s)

[[ 5  5  5  5]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 5  5  5  5  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


You can reshape any array, provided that the new shape has the same number of elements
as the original. otherwise you will get a ValueError

### resize
Method resize modifies the original array’s shape

In [363]:
re_s.resize(20,)

In [364]:
re_s

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [365]:
re_s.resize(4,5)
re_s

array([[ 5,  5,  5,  5,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## List vs. array 

#### Performance -  %timeit

In [11]:
import random 

%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]

5 s ± 81.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

66.8 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### Operators

In [368]:
lst=[2,3,4]
lst*2

[2, 3, 4, 2, 3, 4]

In [369]:
arr=np.array([2,3,4])
arr*2

array([4, 6, 8])

___

In [11]:
lst+2

TypeError: can only concatenate list (not "int") to list

In [371]:
arr

array([2, 3, 4])

In [378]:
arr+np.array([2,2,2])

array([4, 5, 6])

___

In [372]:
lst

[2, 3, 4]

In [373]:
lst2=[8,7,6]
lst+lst2

[2, 3, 4, 8, 7, 6]

In [374]:
arr

array([2, 3, 4])

In [375]:
arr2=np.array([8,7,6])

arr+arr2

array([10, 10, 10])

___

In [376]:
lst**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [377]:
arr**2

array([ 4,  9, 16], dtype=int32)

___

## Broadcasting
Normally, the arithmetic operations require as operands two arrays of the same size and
shape. When one operand is a single value, called a scalar, NumPy performs the elementwise
calculations as if the scalar were an array of the same shape as the other operand, but
with the scalar value in all its elements. This is called broadcasting

In [379]:
arr+ np.array([2,2,2])

array([4, 5, 6])

In [380]:
arr + 2 #brodcasted 2 to a (3,) shape

array([4, 5, 6])

In [381]:
mat=np.array([[1,2,3],[4,4,4],[9,8,7]])
mat

array([[1, 2, 3],
       [4, 4, 4],
       [9, 8, 7]])

In [382]:
mat.shape

(3, 3)

In [22]:
vec=np.array([-2,-2,-2])
vec.shape

(3,)

In [23]:
mat*vec 

array([[ -2,  -4,  -6],
       [ -8,  -8,  -8],
       [-18, -16, -14]])

### element-wise product

1) by np.multiply

In [383]:
np.multiply(mat,vec)

array([[ 2,  4, 12],
       [ 8,  8, 16],
       [18, 16, 28]])

2) by *

In [384]:
mat*vec

array([[ 2,  4, 12],
       [ 8,  8, 16],
       [18, 16, 28]])

### element-wise summation

1)by np.add

In [385]:
np.add(arr,arr2)

array([10, 10, 10])

2) by +

In [386]:
arr+arr2

array([10, 10, 10])

### element-wise exponentiation

1) np.power

In [387]:
np.power(arr,3)

array([ 8, 27, 64], dtype=int32)

3) by **

In [388]:
arr**3

array([ 8, 27, 64], dtype=int32)

### element-wise subtraction 

1) by np.subtract

In [389]:
np.subtract(arr,2)

array([0, 1, 2])

2) by -

In [198]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4])

### element-wise division

1) by np.divide

In [390]:
np.divide(arr,20)

array([0.1 , 0.15, 0.2 ])

2) by /

In [391]:
arr/20

array([0.1 , 0.15, 0.2 ])

## Comparison arrays
Comparisons are
performed element-wise

In [392]:
arr

array([2, 3, 4])

In [27]:
arr>2

array([False,  True,  True])

In [393]:
arr2

array([8, 7, 6])

In [29]:
arr==arr2

array([False, False, False])

## NumPy Calculation Methods (sum, min, max, mean, std  and var)

In [3]:
grades = np.array([[87, 96, 70], [100, 87, 90],[94, 77, 90], [100, 81, 82]])
grades.shape

(4, 3)

In [395]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [396]:
grades.sum()

1054

In [34]:
grades.sum(axis=0) #on all rows

array([381, 341, 332])

In [35]:
grades.sum(axis=1) #on all columns

array([253, 277, 261, 263])

In [397]:
grades.min()

70

In [38]:
grades.min(axis=0) #on all rows

array([87, 77, 70])

In [39]:
grades.min(axis=1) #on all columns

array([70, 87, 77, 81])

In [398]:
grades.max()

100

In [399]:
grades.max(axis=0) #on all rows

array([100,  96,  90])

In [400]:
grades.max(axis=1) #on all columns

array([ 96, 100,  94, 100])

In [401]:
grades.std()

8.792357792739987

In [45]:
grades.std(axis=0)#on all rows

array([5.35607132, 7.15454401, 8.18535277])

In [46]:
grades.std(axis=1) #on all columns

array([10.78064109,  5.55777733,  7.25718035,  8.7305339 ])

In [47]:
grades.var()

77.30555555555556

In [48]:
grades.var(axis=0) #on all rows

array([28.6875, 51.1875, 67.    ])

In [49]:
grades.var(axis=1)#on all columns

array([116.22222222,  30.88888889,  52.66666667,  76.22222222])

___

In [402]:
np.sqrt(grades.var())

8.792357792739987

In [403]:
grades.std()

8.792357792739987

## Indexing and Slicing
One-dimensional arrays can be indexed and sliced using the same syntax and techniques
we demonstrated in the “Sequences: Lists and Tuples”. but higher dimensions are different !

In [57]:
arr=np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [58]:
arr[0]

0

In [404]:
arr[:3]

array([2, 3, 4])

In [405]:
arr[-1]

4

In [406]:
arr[-3:]

array([2, 3, 4])

### Indexing with Two-Dimensional arrays

In [409]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [410]:
grade_lst=[list(row) for row in grades]
grade_lst

[[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]]

In [411]:
#for array indexing :
grades[0,0] # row 0, column 0

87

In [412]:
#for list indexing
grade_lst[0][0] # row 0, column 0

87

## Selecting a Subset of a Two-Dimensional array’s Rows
To select a single row, specify only one index in square brackets

In [413]:
grades[0]

array([87, 96, 70])

In [414]:
grades[3]

array([100,  81,  82])

#### To select multiple sequential rows, use slice notation

In [80]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [415]:
grade_lst[0:2]

[[87, 96, 70], [100, 87, 90]]

In [418]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [417]:
grades[[0, 3]]

array([[ 87,  96,  70],
       [100,  81,  82]])

In [421]:
grade_lst[1:4]

[[100, 87, 90], [94, 77, 90], [100, 81, 82]]

## Selecting a Subset of a Two-Dimensional array’s Columns
You can select subsets of the columns by providing a tuple specifying the rows and columns to select

In [422]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [423]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [424]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [111]:
grades[:, [0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [425]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [426]:
 grades[0:2,1]

array([96, 87])

In [427]:
grade_lst

[[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]]

In [104]:
 #for lists: 
[row[1] for row in grade_lst[0:2]]

[96, 87]

### Transposing rows and columns
The T attribute returns a
transposed view (shallow copy) of the array.

In [428]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [429]:
grades.T

array([[ 87, 100,  94, 100],
       [ 96,  87,  77,  81],
       [ 70,  90,  90,  82]])

In [430]:
np.transpose(grades)

array([[ 87, 100,  94, 100],
       [ 96,  87,  77,  81],
       [ 70,  90,  90,  82]])

### combine arrays

In [431]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [432]:
gr=np.array([[20,40,60]])

np.vstack((grades,gr))

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82],
       [ 20,  40,  60]])

In [433]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [434]:
gr2=np.array([[1,2],[2,7],[3,6],[5,4]])
np.hstack((grades,gr2))

array([[ 87,  96,  70,   1,   2],
       [100,  87,  90,   2,   7],
       [ 94,  77,  90,   3,   6],
       [100,  81,  82,   5,   4]])

### empty_like
Creates an empty matrix with the same shape as x filled with random numbers

In [199]:
y = np.empty_like(grades)
y

array([[-1717986918,  1068079513, -1717986918],
       [ 1069128089,   858993459,  1069757235],
       [-1717986918,  1070176665,           0],
       [ 1070596096,   858993459,  1070805811]])

### more on NumPy Calculation Methods

$e^x$  :


In [211]:
np.exp(1) 

2.718281828459045

In [435]:
a=np.array([10,2,np.exp(1)])
a

array([10.        ,  2.        ,  2.71828183])

In [436]:
print(np.log10(a))
print(np.log(a)) #with base e
print(np.log2(a))

[1.         0.30103    0.43429448]
[2.30258509 0.69314718 1.        ]
[3.32192809 1.         1.44269504]


In [206]:
b=np.array([-1,-1,-1])
np.abs(b)

array([1, 1, 1])

In [212]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


### Convert an array to a different type

In [437]:
a=np.array([2.1,2,3,4])
a

array([2.1, 2. , 3. , 4. ])

In [216]:
a.astype(int) 

array([2, 2, 3, 4])


# Matrix multiplication 

In [439]:
vec=np.array([2,2,4])

mat=np.array([[1,2,3],[1,1,1],[3,3,3]])

print(vec,'\n')
print(mat)

[2 2 4] 

[[1 2 3]
 [1 1 1]
 [3 3 3]]


In [440]:
np.dot(vec,mat)

array([16, 18, 20])

In [441]:
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

In [442]:
result

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]

In [443]:
np.dot(X,Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

### squeeze
Return an array with all unit-length dimensions squeezed out.

In [450]:
a=np.array([[[1],[2],[3]]])
a.shape

(1, 3, 1)

In [451]:
np.squeeze(a)

array([1, 2, 3])

In [449]:
np.squeeze(a).shape

(3,)

In [444]:
b=np.array([[[1]]])
b.shape

(1, 1, 1)

In [445]:
np.squeeze(b)

array(1)

In [446]:
np.squeeze(b).shape

()

### repeat

In [252]:
np.repeat(3,5)

array([3, 3, 3, 3, 3])

___

### argmax
Return the first **index** of the largest value in self.

In [4]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [5]:
grades.argmax()

3

In [453]:
grades.argmax(axis=0)

array([1, 0, 1], dtype=int64)

In [454]:
grades.argmax(axis=1)

array([1, 0, 0, 0], dtype=int64)

In [455]:
grades.trace()

264

In [456]:
np.prod([1,2,3])

6